global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  #########GaphQL#########

  - job_name: 'user_graphql'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-graphql:8001']

  - job_name: 'message_graphql'
    metrics_path: /metrics
    static_configs:
      - targets: ['message-graphql:8011']

  - job_name: 'event_graphql'
    metrics_path: /metrics
    static_configs:
      - targets: ['event-graphql:8021']

  #########WebHook#########

  - job_name: 'user_webhook'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-webhook:8003']

  - job_name: 'message_webhook'
    metrics_path: /metrics
    static_configs:
      - targets: ['message-webhook:8004']

  - job_name: 'event_webhook'
    metrics_path: /metrics
    static_configs:
      - targets: ['event-webhook:8023']

  #########GRPC#########

  - job_name: 'user_grpc'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-grpc:50052']

  - job_name: 'message_grpc'
    metrics_path: /metrics
    static_configs:
      - targets: ['message-grpc:50053']

  - job_name: 'event_grpc'
    metrics_path: /metrics
    static_configs:
      - targets: ['event-grpc:50062']

