global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'python_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['python_service:8000']

  # - job_name: 'java_service'
  #   metrics_path: /actuator/prometheus
  #   static_configs:
  #     - targets: ['java_service:8080']
