version: "3.8"

services:

  user-graphql:
    build: ../python/services/user-service/user-service-graphql
    image: user-graphql:dev
    container_name: user-graphql
    ports:
      - "8001:8001"   
    networks:
      - testnet

  message-graphql:
    build: ../python/services/message-service/message-service-graphql
    image: message-graphql:dev
    container_name: message-graphql
    ports:
      - "8011:8011"
    networks:
      - testnet

  event-graphql:
    build: ../python/services/event-service/event-service-graphql
    image: event-graphql:dev
    container_name: event-graphql
    ports:
      - "8021:8021"
    networks:
      - testnet


  user-grpc:
    build: ../python/services/user-service/user-service-grpc
    image: user-grpc:dev
    container_name: user-grpc
    ports:
      - "50051:50051"     
      - "50052:50052"     
    networks:
      - testnet

  message-grpc:
    build: ../python/services/message-service/message-service-grpc
    image: message-grpc:dev
    container_name: message-grpc
    ports:
      - "50054:50054"
      - "50053:50053"
    networks:
      - testnet

  event-grpc:
    build: ../python/services/event-service/event-service-grpc
    image: event-grpc:dev
    container_name: event-grpc
    ports:
      - "50061:50061"
      - "50062:50062"
    networks:
      - testnet

  user-webhook:
    build: ../python/services/user-service/user-service-webhook
    image: user-webhook:dev
    container_name: user-webhook
    ports:
      - "8003:8003"
    networks:
      - testnet

  message-webhook:
    build: ../python/services/message-service/message-service-webhook
    image: message-webhook:dev
    container_name: message-webhook
    ports:
      - "8004:8004"
    networks:
      - testnet

  event-webhook:
    build: ../python/services/event-service/event-service-webhook
    image: event-webhook:dev
    container_name: event-webhook
    ports:
      - "8023:8023"
    networks:
      - testnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - testnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - testnet
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  testnet:
    driver: bridge

