version: "3.8"

services:
  # python_service:
  #   build: ../python/services/user-service/off
  #   container_name: user-service-python
  #   ports:
  #     - "8000:8000"        
  #   networks:
  #     - testnet
  #   depends_on:
  #     - prometheus

  user-graphql:
    build: ../python/services/user-service/user-service-graphql
    image: user-graphql:dev
    container_name: user-graphql
    ports:
      - "8001:8001"   
    networks:
      - testnet

  user-grpc:
    build: ../python/services/user-service/user-service-grpc
    image: user-grpc:dev
    container_name: user-grpc
    ports:
      - "50051:50051"     
      - "50052:50052"     
    networks:
      - testnet

  user-webhook:
    build: ../python/services/user-service/user-service-webhook
    image: user-webhook:dev
    container_name: user-webhook
    ports:
      - "8003:8003"
    networks:
      - testnet

  # Uncomment and configure Java service when ready
  # java_service:
  #   build: ../java/services/user-service
  #   container_name: user-service-java
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - testnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - testnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - testnet
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  testnet:
    driver: bridge

